# This is a basic workflow to help you get started with Actions

name: Functional tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    container:
      image: biobakery/kneaddata:latest
      
    steps:
    # check out repository under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2

    - name: Install
      run: cd $GITHUB_WORKSPACE && python3 setup.py install
    
    - name: Help
      run: kneaddata --help
    
    - name: Run basic test with small demo files
      run: kneaddata --unpaired examples/demo.fastq --output output_folder -db examples/
